# Site
title: "Open Science Community Delft"
description: >
  A community of researchers, educators and staff who are interested in open science.
logo: ''
email: team@openscience-delft.org
repository: osc-delft/osc-delft-website
twitter: OSCDelft
url: https://openscience-delft.org

collections:
  posts:
    permalink: /posts/:year/:month/:day/:title/

includes_dir: .

plugins:
  - jekyll-last-modified-at
